#!/bin/bash -eu

cd $(dirname $0)/..

docker run --rm -t \
  -v ${PWD}/cfg:/cfg \
  -e BUILDKITE_MESSAGE \
  -e BUILDKITE_COMMIT \
  -e BUILDKITE_BUILD_CREATOR_EMAIL \
  -e BUILDKITE_BUILD_URL \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SECURITY_TOKEN \
  -e AWS_DEFAULT_REGION \
  nrops:1 \
  "$@"
